Add custom listener in constructor + default value
lmarkus/hubot-conversation pull request #21
Opened 2017-08-31 14:24 UTC by viking225

See issue  #18

2017-08-31 16:51 UTC, lmarkus requested changes
You'll also need to update the documentation.

2017-08-31 16:51 UTC, lmarkus commented on lib/index.js
> +            return (customListener) ? _talkingTo[id] : false;
In this line you may want to do `customListener()`. 

Right now, you're checking to see that the function is defined, rather than invoking it.

2017-08-31 16:51 UTC, lmarkus commented on lib/index.js
> +    //Default listener to ovverride with your own
Minor typo in `ovverride`

2017-09-04 22:50 UTC, viking225 commented
Sorry for the mess, i had some issues to make the tests work with grunt.

2017-09-04 23:57 UTC, lmarkus approved these changes

2017-09-04 23:57 UTC, merged

2017-09-04 23:58 UTC, lmarkus commented
Thank you.

I have another open PR. I'll wait for that one to complete and then will do a release

2017-09-05 00:11 UTC, viking225 commented
Sorry but GitHub is apparently handling markdown in a slightly different way, i did a commit to fix the bad documentation rendering.